-- بروزرسانی مستقیم APK برای نسخه Native Kotlin
-- این فایل را فقط روی پروژه اصلی Supabase اجرا کنید:
-- https://eazwuyrymsvdkwckdpco.supabase.co

begin;

create table if not exists public.app_version (
    id bigint generated by default as identity primary key
);

alter table public.app_version
    add column if not exists id bigint generated by default as identity,
    add column if not exists version_code integer not null default 1,
    add column if not exists version_name text not null default '1.0.0',
    add column if not exists notes_fa jsonb not null default '[]'::jsonb,
    add column if not exists apk_url text not null default '',
    add column if not exists apk_sha256 text,
    add column if not exists apk_size_bytes bigint,
    add column if not exists is_required boolean not null default false,
    add column if not exists is_active boolean not null default false,
    add column if not exists published_at timestamptz not null default now(),
    add column if not exists created_at timestamptz not null default now();

-- هیچ ردیف فعال با URL ناامن یا ناقص در اختیار برنامه قرار نگیرد.
update public.app_version
set is_active = false
where is_active
  and apk_url !~* '^https://[^[:space:]]+$';

-- فقط جدیدترین ردیف فعال باقی بماند.
with ranked as (
    select id,
           row_number() over (order by version_code desc, published_at desc, id desc) as row_number
    from public.app_version
    where is_active
)
update public.app_version as version
set is_active = false
from ranked
where version.id = ranked.id
  and ranked.row_number > 1;

create unique index if not exists app_version_one_active_idx
    on public.app_version ((is_active))
    where is_active;

create index if not exists app_version_code_idx
    on public.app_version (version_code desc);

alter table public.app_version enable row level security;

revoke all on table public.app_version from anon, authenticated;
grant select on table public.app_version to anon, authenticated;

drop policy if exists "read active app version" on public.app_version;
create policy "read active app version"
on public.app_version
for select
to anon, authenticated
using (is_active = true);

-- RPC سازگار برای کلاینت‌های دیگر؛ برنامه Kotlin مستقیماً همان ردیف RLSشده را می‌خواند.
-- DROP برای این است که اگر نسخه قدیمی تابع خروجی دیگری داشت، مهاجرت متوقف نشود.
drop function if exists public.check_app_update(integer);
create function public.check_app_update(p_current_version_code integer)
returns table (
    version_code integer,
    version_name text,
    notes_fa jsonb,
    apk_url text,
    apk_sha256 text,
    apk_size_bytes bigint,
    is_required boolean
)
language sql
stable
security invoker
set search_path = public
as $$
    select
        version.version_code::integer,
        version.version_name::text,
        to_jsonb(version.notes_fa),
        version.apk_url::text,
        version.apk_sha256::text,
        version.apk_size_bytes::bigint,
        version.is_required::boolean
    from public.app_version as version
    where version.is_active = true
      and version.version_code > p_current_version_code
    order by version.version_code desc
    limit 1;
$$;

grant execute on function public.check_app_update(integer) to anon, authenticated;

-- مخزن عمومی فقط برای دانلود APK؛ نوشتن فقط از محیط مدیریتی انجام می‌شود.
insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'app-updates',
    'app-updates',
    true,
    209715200,
    array['application/vnd.android.package-archive', 'application/octet-stream']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public read app update APK" on storage.objects;
create policy "public read app update APK"
on storage.objects
for select
to public
using (bucket_id = 'app-updates');

commit;

notify pgrst, 'reload schema';

-- پس از ساخت APK Release و آپلود آن در bucket بالا، ابتدا این دو دستور را در WSL اجرا کنید:
--   sha256sum app-release.apk
--   stat -c%s app-release.apk
-- سپس نمونه زیر را با مقادیر واقعی اجرا کنید. version_code باید دقیقاً با Gradle/APK برابر باشد.
--
-- begin;
-- update public.app_version set is_active = false where is_active;
-- insert into public.app_version (
--     version_code, version_name, notes_fa, apk_url,
--     apk_sha256, apk_size_bytes, is_required, is_active
-- ) values (
--     2,
--     '1.1.0',
--     '["افزودن منوی همبرگری", "دانلود و نصب مستقیم بروزرسانی"]'::jsonb,
--     'https://eazwuyrymsvdkwckdpco.supabase.co/storage/v1/object/public/app-updates/exam-app-1.1.0.apk',
--     'SHA256_64_HEX_CHARACTERS',
--     12345678,
--     false,
--     true
-- );
-- commit;
